# Uncomment the next line to define a global platform for your project

platform :ios, '12.0'
use_frameworks!

target 'TV Shows' do
  # Pods for TV Shows
  pod 'SVProgressHUD'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 6.0'
end
